### ISSUE TITLE
Gradle依赖失败了

### ISSUE THREAD

**Issue by qq157755587** [saiwu-bigkoo/Android-ConvenientBanner#1]
在gradle中加上 compile 'com.bigkoo:convenientbanner:1.0.0' 一直没有办法正常引用，只能下载aar粘贴到工程中。
另外你的android:icon会与调用者的android:icon冲突，应该把library moule中的android:icon删掉。

**Comment by saiwu-bigkoo** [comment]
请问没有办法正常引用的错误是提示什么呢？

**Comment by qq157755587** [comment]
Sorry，我重新折腾又就能正常引用了。可能是我的环境问题吧。

**Comment by qq157755587** [comment]
顺便提一下，setPages方法的第二个参数类型最好用List，而不是ArrayList。

**Comment by qq157755587** [comment]
抱歉没有一次讲完，我是边用边提建议。。。
在notifyDataSetChange里面new Adapter很奇怪啊，如果调用多次notifyDataSetChange就会new多个Adapter实例，如果不调用就直接挂掉了（我刚才就没调用）。把notifyDataSetChange的代码放在setPages的末尾会不会更合理些，不要让用户自己调用。

**Comment by saiwu-bigkoo** [comment]
你好，notifyDataSetChange确实有点多余，已经在1.0.3版中去掉了，也改为List
