### ISSUE TITLE
图片比例自适应的问题

### ISSUE THREAD

**Issue by LiuTaw** [saiwu-bigkoo/Android-ConvenientBanner#100]
您好，使用您的广告滚动非常赞，帮助很大，自定义程度也很高，美中不足就是图片不能自适应大小，希望能解决一下

**Comment by saiwu-bigkoo** [comment]
你说的是控件高度无法自动适应图片高度吧？实在支持不了，比如网络图片请求回来之后才能计算大小，这些都无法预估

**Comment by badcodeln** [comment]
Glide回调获取图片大小，之后代码里重新设置banner的宽高，这样可以实现自适应。

**Comment by LiuTaw** [comment]
谢啦，其实不一定要实现自适应，用图片的一些type属性也可以，比如说centerinside

**Comment by badcodeln** [comment]
type属性的话有可能无法完整显示图片，如果需求是不拉伸、完整显示图片，推荐用回调设置。
