### ISSUE TITLE
setManualPageable(false)后,setOnItemClickListener点击事件失效

### ISSUE THREAD

**Issue by forzajuve** [saiwu-bigkoo/Android-ConvenientBanner#102]
比如我们bannar图,只有一个item数据的时候,一般都会希望它不能滑动,于是设置setManualPageable(false),没想到连点击事件都屏蔽了,不能因为不让滑动就点击事件都屏蔽了吧

    @Override
    public boolean onTouchEvent(MotionEvent ev) {
        if (isCanScroll) {
            if (onItemClickListener != null) {
                switch (ev.getAction()) {
                    case MotionEvent.ACTION_DOWN:
                        oldX = ev.getX();
                        break;

                    case MotionEvent.ACTION_UP:
                        newX = ev.getX();
                        if (Math.abs(oldX - newX) < sens) {
                            onItemClickListener.onItemClick((getRealItem()));
                        }
                        oldX = 0;
                        newX = 0;
                        break;
                }
            }
            return super.onTouchEvent(ev);
        } else
            return false;
    }

**Comment by saiwu-bigkoo** [comment]
你判断只有一个的时候，设置不循环模式应该可以解决

**Comment by forzajuve** [comment]
@saiwu-bigkoo  多谢
