### ISSUE TITLE
把banner添加到recyclerview中，下拉后返回顶部，自动翻页时间失效，翻动过快

### ISSUE THREAD

**Issue by lucheng0522** [saiwu-bigkoo/Android-ConvenientBanner#103]
把banner添加到recyclerview中的一个viewtype中。下拉后返回顶部。banner翻页速度会非常快

**Comment by saiwu-bigkoo** [comment]
demo中有个recycler view 例子，你可以参考下

**Comment by asker517** [comment]
same issue

**Comment by xieyuanwin** [comment]
一样的问题，你解决了吗@lucheng0522

**Comment by lucheng0522** [comment]
我换了一个。“https://github.com/H07000223/FlycoBanner_Master/blob/master/README_CN.md” 他写的很好






------------------ 原始邮件 ------------------
发件人: "xieyuan";<notifications@github.com>;
发送时间: 2016年6月8日(星期三) 上午10:28
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 
抄送: "シ菰独の渡濄"<1149097472@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [saiwu-bigkoo/Android-ConvenientBanner] 把banner添加到recyclerview中，下拉后返回顶部，自动翻页时间失效，翻动过快 (#103)




一样的问题，你解决了吗@lucheng0522 
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




我换了别人的 。https://github.com/H07000223/FlycoBanner_Master/blob/master/README_CN.md  写的很好

**Comment by xieyuanwin** [comment]
这个库的作者不积极回应大家的问题

**Comment by xieyuanwin** [comment]
@lucheng0522 这个FlycoBanner_Master可以使用自己定义加载图片加载库吗？比如Glide、Universal-Image-Loader_Master

**Comment by xieyuanwin** [comment]
我做了测试，没有问题，多次调用startTurning会导致自动翻页时间失效，翻动过快，使用如下的代码可以解决：if(!mConvenientBannerr.isTurning()){mConvenientBannerr.startTurning();}

**Comment by SomnusWu** [comment]
我也遇到这个问题 ，我是吧ConvenientBanner 添加到recyclerView的头部 然后在Fragment中
` // 开始自动翻页
    @Override
    public void onResume() {
        super.onResume();
        //开始自动翻页
        if (mConvenientBanner != null && !mConvenientBanner.isTurning()) {
            mConvenientBanner.stopTurning();
            mConvenientBanner.startTurning(Constants.SCROLLTIME);
            LogManag.d("自动翻页");
        }
    }`

`// 停止自动翻页
    @Override
    public void onPause() {
        super.onPause();
        LogManag.d("onPause");
        //停止翻页
        mConvenientBanner.stopTurning();
    }`

还是会出现问题.
重现步骤: 把recyclerView上拉 让ConvenientBanner  不可见 ，然后点击到 另外的tab ，再次回到有ConvenientBanner 页面 ，出现滚动过快的情况

**Comment by Bleach1** [comment]
我的问题是上拉加载的时候轮播图自动滚动停止 手动划一下才好使

**Comment by fengjundev** [comment]
定时任务实现的问题 各位修改下startScroll里面的逻辑 每次调用要清空原有定时任务即可
