### ISSUE TITLE
SwipeRefreshLayout嵌套滑动冲突

### ISSUE THREAD

**Issue by growding** [saiwu-bigkoo/Android-ConvenientBanner#106]
SwipeRefreshLayout-->ScrollView --> Banner
导致滑动冲突,我自定义了SwipeRefreshLayout有卡顿现象,不知道该如何解决

**Comment by saiwu-bigkoo** [comment]
Demo 中有CustomSwipeToRefresh 可以参考下

**Comment by growding** [comment]
谢谢!demo有例子
