### ISSUE TITLE
banner有时候突然翻页速度会非常快？

### ISSUE THREAD

**Issue by MIkeeJY** [saiwu-bigkoo/Android-ConvenientBanner#107]
我设置的3秒翻页  但是有时候突然会不到1秒就翻页了！这是为什么呢？

**Comment by MIkeeJY** [comment]
没有嵌套 只是写在布局里，应该是个bug！

**Comment by MIkeeJY** [comment]
只有手动滑动一下 时间才会正常，希望能看下哈~

**Comment by yogn** [comment]
我也遇到了，切换Fragment时，再回来Fragment中时，Fragment中的ViewPager速度就会变化！！！！

**Comment by MIkeeJY** [comment]
@yogn 确实是这个样子的 主要是fragment 重新create的时候

**Comment by XanthusL** [comment]
我也遇到了 , 手动滑动一下才正常

**Comment by asker517** [comment]
```java
  @Override
  protected void onAttachedToWindow() {
    super.onAttachedToWindow();
    if (viewPager != null) {
      viewPager.requestLayout(); //prevent viewpager strange scroll behavior.
    }
  }
```
我暂时是这样解决的，在``ConvenientBanner``中添加以上代码，个人感觉和`viewpager`内部的`mFirstLayout`成员变量有一定关系，可以观察到每当出现这种快速的翻页，感觉是因为`viewpager`内部`onAttachedToWindow()`方法中把这个变量只为true，所以当调用`setCurrentItem()`方法的时候走了另外一条分支，和正常滚动的时候是不一样的。所以我这里调用了viewpager的requestLayout，把`mFirstLayout`置回false，然后表现比较正常。可能不是一个比较好的解决方法。。但是有效。
@MIkeeJY @yogn @XanthusL @saiwu-bigkoo

**Comment by XanthusL** [comment]
@asker517 我通过接口分别在onResume和onPause使它开始和停止翻页
似乎解决了

**Comment by asker517** [comment]
您是说用自带的开始和停止方法么？在我的案例中貌似并不能解决
2016年5月24日 20:00，"XanthusL" <notifications@github.com>写道：

**Comment by xieyuanwin** [comment]
真的要解决下了，刷新就会出现这个问题，要用手滑动一下才正常，求解决

**Comment by xieyuanwin** [comment]
我做了测试，没有问题，多次调用startTurning会导致自动翻页时间失效，翻动过快，使用如下的代码可以解决：if(!mConvenientBannerr.isTurning()){mConvenientBannerr.startTurning();}

**Comment by MIkeeJY** [comment]
@xieyuanwin  good job man!

**Comment by rdshoep** [comment]
@xieyuanwin good idea!  [stopTurning()在列表中并不起作用。初步猜测是调用stopTurnning时处于分离状态，导致未能准确移除runnableTask``](http://stackoverflow.com/questions/9768706/why-is-posting-cancelled-a-runnable-on-a-view-and-handler-result-in-different)

**Comment by Sanjay-F** [comment]
@xieyuanwin 
这个似乎还是不能解决问题，跳去别的页面，再回来这个fragment还是会加快速度
