### ISSUE TITLE
使用Glide加载网络图片的时候好像会失败

### ISSUE THREAD

**Issue by DiskyZhs** [saiwu-bigkoo/Android-ConvenientBanner#110]
代码如下：
 private class NewsImageHolderView implements Holder<TrafficNews> {
        private ImageView imageView;
        private Context context;

```
    public NewsImageHolderView(Context context) {
        this.context = context;
    }

    @Override
    public View createView(Context context) {  //冲刷界面
        imageView = new ImageView(context);
        imageView.setScaleType(ImageView.ScaleType.FIT_XY);
        return imageView;
    }

    @Override
    public void UpdateUI(Context context, final int position, TrafficNews data) { //绑定数据
        Glide.with(this.context).load(HttpRequstConstant.BASE_IP + data.getPicture()).into(imageView);
    }
}
```

   mNewsBanner.setPages(new CBViewHolderCreator<NewsImageHolderView>() {
            @Override
            public NewsImageHolderView createHolder() {
                return new NewsImageHolderView(TrafficNoticeActivity.this);
            }
        }, mHeadDataList).setPageIndicator(new int[]{R.mipmap.circle_indicator, R.mipmap.circle_indicator_choosen}).setPageIndicatorAlign(ConvenientBanner.PageIndicatorAlign.ALIGN_PARENT_RIGHT);__

**Comment by DiskyZhs** [comment]
DataChangeNotify cause it，i found

**Comment by zhangcf2012** [comment]
你是 怎么改的代码
