### ISSUE TITLE
xml设置canLoop设置为false存在bug

### ISSUE THREAD

**Issue by YuzurihaInori** [saiwu-bigkoo/Android-ConvenientBanner#113]
具体表现为，viewpager的CurrentItem为最后一页，当滑动到第一页时自动跳转至最后一页，java代码里设置setCanLoop不存在问题。

原因CBLoopViewPager的canLoop变量只有在setCanLoop里赋值，setAdapter方法里并未对该变量赋值，因此xml里设置canLoop为false存在问题。

**Comment by CrazyTaro** [comment]
同样发现这个问题,但是亲测同时在xml与代码中设置了false也是无效的.还是会出现这个bug现象.

唯一的解决方案是先设置为true,绑定后再设置为false即可常显示第一页不再是自动跳转到最后一页了.

```
mCbBanner.setCanLoop(true);
//设置的代码
ViewUtil.setBanner(mCbBanner, new SplashBannerCreator(), itemList);
mCbBanner.setCanLoop(false);
```
