### ISSUE TITLE
指示器圆点 imagview 能设置宽高就好了 

### ISSUE THREAD

**Issue by fuxianwen** [saiwu-bigkoo/Android-ConvenientBanner#114]

**Comment by zhudongya123** [comment]
`LinearLayout indicatorArray = (LinearLayout) getActivity().findViewById(com.bigkoo.convenientbanner.R.id.loPageTurningPoint);
        for (int i = 0; i < indicatorArray.getChildCount(); i++) {
            ImageView imageView = (ImageView) indicatorArray.getChildAt(i);
            //这里的ImageView就是指示器ImageView的实例
        }`
