### ISSUE TITLE
ViewPager 嵌套 banner 之后，banner 滑动事件失效

### ISSUE THREAD

**Issue by Freelander** [saiwu-bigkoo/Android-ConvenientBanner#118]
在开发当中，我使用 ViewPager + Fragment 实现滑动 TabLayout 切换，在其中一个fragment中嵌套一个 banner，发现 banner 不能进行左右滑动了，有没有办法解决呢？？

**Comment by saiwu-bigkoo** [comment]
这是被ViewPager抢了事件，重写下ViewPager的分发逻辑
