### ISSUE TITLE
adapter错误

### ISSUE THREAD

**Issue by c78526751** [saiwu-bigkoo/Android-ConvenientBanner#120]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1200, found: 0 Pager id: com.pengcent.twostudyado:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapte

**Comment by yifan-2013** [comment]
如果改变了adapter数据，必须执行notifyDataSetChanged。我只去clear数据后没有调用notifyDataSetChanged，又去重新设置adapter就报了这个错，所以我在clear数据之后先调用notifyDataSetChanged再重新设置adapter就正常了
