### ISSUE TITLE
canLoop属性问题

### ISSUE THREAD

**Issue by a710398739** [saiwu-bigkoo/Android-ConvenientBanner#121]
在布局文件给ConvenientBanner设置app:canLoop="false"时，运行后 会自动跳到最后一页，然而设置app:canLoop="true"时，就正常了。求解答 是怎么回事。。。。

**Comment by WosLovesLife** [comment]
v2.0.5版, 当图片只有一张的时候也可以左右滑动, 即使我设置了canLoop()为false 也可以向右滑动一页

**Comment by saiwu-bigkoo** [comment]
@WosLovesLife 当只有一页的时候你可以设置 setManualPageable(false);//设置不能手动影响
