### ISSUE TITLE
希望能增加textview文字标题显示功能

### ISSUE THREAD

**Issue by lty87** [saiwu-bigkoo/Android-ConvenientBanner#123]
并可以简单地控制 显示或不显示。
还有是否可以垂直方向文字滚动，像淘宝首页那样

**Comment by abbenyyyyyy** [comment]
这个自己读一下源码很容易自己实现的，授人以鱼不如授人以渔

**Comment by saiwu-bigkoo** [comment]
同意楼上，已经提供了Listener来监听翻页滚动，至于你要文字滚动可以根据这个Listener进行关联即可
