### ISSUE TITLE
Indicator尺寸的问题

### ISSUE THREAD

**Issue by iboying** [saiwu-bigkoo/Android-ConvenientBanner#128]
我把demo的indicator图片导入到mipmap，结果显示出来的指示器很大，这个尺寸怎么做适配好呢？
![image](https://cloud.githubusercontent.com/assets/10523771/16255274/f8022982-387a-11e6-8738-e061a3a05330.png)

**Comment by saiwu-bigkoo** [comment]
按项目位置放就行了，如果硬要放别的位置那么文件大小自己按实际需求修改了。

**Comment by iboying** [comment]
好的  解决了   放的资源文件位置不对   谢谢
