### ISSUE TITLE
我在xml自定义指示器，并且更改半径之后，指示器任然很小，求解？

### ISSUE THREAD

**Issue by ZLdeSpirit** [saiwu-bigkoo/Android-ConvenientBanner#134]
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="#F16702"/>
    <corners android:radius="13dp"/>
</shape>

**Comment by saiwu-bigkoo** [comment]
你确定显示的是你自定义的指示器而不是默认的？如果还很小你自己仔细看看shape相关知识了，这个我帮你解不了

**Comment by ZLdeSpirit** [comment]
我在setPageIndicator()设置自定义的指示器的，有默认的吗？

**Comment by saiwu-bigkoo** [comment]
demo中就是设置默认的点，你不需要调用setPageIndicator，只需要监听Listener来控制你的点就可以了。

**Comment by lolilicker** [comment]
我也遇到了这个问题，xml中写的indicator显示出来特别小

**Comment by TigerSkinCat** [comment]
你们是怎么设置的，我也遇到 到问题。设置完不对
