### ISSUE TITLE
不轮播时你的viewpage会指向最后一页

### ISSUE THREAD

**Issue by gaobin881201** [saiwu-bigkoo/Android-ConvenientBanner#138]
不轮播时你的viewpage会指向最后一页，无论我怎么设置 当前item的值都会被覆盖
  public int toRealPosition(int position) {
        int realCount = getRealCount();
        if (realCount == 0)
            return 0;
        int realPosition = position % realCount;
        return realPosition;
    }

```
@Override
public int getCount() {
    return canLoop ? getRealCount()*MULTIPLE_COUNT : getRealCount();
}
```

**Comment by saiwu-bigkoo** [comment]
请问你的意思是，点击返回的 位置 无论是哪个位置都返回最后一个item 位置？

**Comment by sldboy** [comment]
我也碰到这个问题了.
