### ISSUE TITLE
IllegalAccessException

### ISSUE THREAD

**Issue by Mr-GX** [saiwu-bigkoo/Android-ConvenientBanner#14]
ConvenientBanner类中的setPageTransformer()方法报IllegalAccessException，好像是反射那问题

**Comment by saiwu-bigkoo** [comment]
能再具体点吗

**Comment by Mr-GX** [comment]
![qq20150908185226](https://cloud.githubusercontent.com/assets/9333451/9733057/0333359c-565b-11e5-8509-de624d5e675b.png)

**Comment by saiwu-bigkoo** [comment]
会不会是你的V4包和库的V4包版本不一样而导致呢？

**Comment by saiwu-bigkoo** [comment]
compile('com.bigkoo:convenientbanner:1.0.7') {
exclude module: 'support-v4'
exclude module: 'appcompat-v7'
}
你可以这样排除我包内的冲突
