### ISSUE TITLE
设置自动翻页时间是1秒，有时循环一次后第一页的图片还是用了最后一张

### ISSUE THREAD

**Issue by qq1728744610** [saiwu-bigkoo/Android-ConvenientBanner#147]
同上，还有就是以前一直用LoopingViewPager，后来机器升级到6.0，发现这个库快速滑动一定次数会变得非常卡，在5.x和4.x都没问题，它是在onPageScrollStateChanged里面进行循环切换的，而你的库是在finishupdate，这有什么不同吗？

**Comment by SmallPeas** [comment]
finishupdata在滑动的时候是不允许做数据的加载和更新的，或者说已经加载完毕不在进行更新。onPageScrollStateChanged在监听到页面的滑动后会对数据进行处理，在数据太多的时候就会卡顿。




------------------ 原始邮件 ------------------
发件人: "qq1728744610";<notifications@github.com>;
发送时间: 2016年8月15日(星期一) 下午3:39
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 

主题: [saiwu-bigkoo/Android-ConvenientBanner] 设置自动翻页时间是1秒，有时循环一次后第一页的图片还是用了最后一张 (#147)




同上，还有就是以前一直用LoopingViewPager，后来机器升级到6.0，发现这个库快速滑动一定次数会变得非常卡，在5.x和4.x都没问题，它是在onPageScrollStateChanged里面进行循环切换的，而你的库是在finishupdate，这有什么不同吗？
