### ISSUE TITLE
图片空白

### ISSUE THREAD

**Issue by huweijian5** [saiwu-bigkoo/Android-ConvenientBanner#149]
一开始图片全白，过了3秒后才显示出来，使用glide加载网络图片，一开始以为是没设置占位符，设了之后发现还是一样出现3秒空白

**Comment by saiwu-bigkoo** [comment]
我也是用glide，没发现这种情况。

**Comment by jesse920524** [comment]
@saiwu-bigkoo @huweijian5 请教,我使用glide加载UpdateUI()中的第三个形参data无效,能否给点代码片段参考,万分感谢!!

**Comment by saiwu-bigkoo** [comment]
@jesse920524 你可以断点看看你的data到底有没有值

**Comment by sldboy** [comment]
点击控件出现空白,
