### ISSUE TITLE
adapter bug,

### ISSUE THREAD

**Issue by wangyao5018** [saiwu-bigkoo/Android-ConvenientBanner#15]
如果数据设置两条以上,
例如3条或者4条,上来就直接向左边滑动,控件会被清一下,
您的这个adapter处理我不太看得懂,
下面留一个gif,

http://wy.21bit.cn/test/sa.gif

**Comment by wangyao5018** [comment]
还有一个问题,
我之前用的一个banner裤循环viewpager,
用的是integer.max_value这种方法,
完后我不想自动播放,
就把getcount的值设置成集合的.size(),
能打到不播放的时候,可以不让它往左变滑动,
可以你用的这个方法怎么达到这个目的呢?

**Comment by saiwu-bigkoo** [comment]
不自动播放可以，但不往左也就是停止无限循环是不行的

**Comment by wangyao5018** [comment]
您看我发的那个gif的问题了吗,这个比较严重.不知道怎么解决
