### ISSUE TITLE
自动跳转到最后一页

### ISSUE THREAD

**Issue by chenwulue** [saiwu-bigkoo/Android-ConvenientBanner#151]
我是拿来当引导页的
设置
`canLoop`为false
`stopTurning`
当我停留在第一个页面时，很快会自动跳转到最后页面（我有三个页面）

**Comment by hexianqiao3755** [comment]
你们用这个来做引导页, 是怎么去掉可以滑动的功能的, 就是滑动到最后一张再滑就到第一张了

**Comment by ddswez** [comment]
在xml里设置app:canLoop=false会出现这个问题, 可以在代码中设置 setCanLoop(false) 就没问题了....

**Comment by coding0man** [comment]
我也遇到了这个问题。
三张图片，
如果在xml中设置canloop=false,滑动到第一张的时候回自动切回第三张照片；
如果在java代码中设置convenientbanner.setcanloop(false),就没有问题。
望尽快解决
