### ISSUE TITLE
Glide问题,求助

### ISSUE THREAD

**Issue by jesse920524** [saiwu-bigkoo/Android-ConvenientBanner#153]
UpdateUI中data就是图片的数据源对吗?我如何使用Glide加载所有图片到所有imageView上?以前使用Glide都是一张url加载到一个ImageView实例上的,求助.
以下是我所有代码:

public class TabFragment extends android.support.v4.app.Fragment implements OnItemClickListener {
    private View view;
    private ConvenientBanner vp_tablayout_banner;
    private RecyclerView rv_tablayout_rv;

    private List<String> imgDatas;//Banner的图片List
    private String[] images = {
            "http://img2.imgtn.bdimg.com/it/u=3093785514,1341050958&fm=21&gp=0.jpg",
            "http://img2.3lian.com/2014/f2/37/d/40.jpg",
            "http://d.3987.com/sqmy_131219/001.jpg",
            "http://img2.3lian.com/2014/f2/37/d/39.jpg",
            "http://www.8kmm.com/UploadFiles/2012/8/201208140920132659.jpg",
            "http://f.hiphotos.baidu.com/image/h%3D200/sign=1478eb74d5a20cf45990f9df460b4b0c/d058ccbf6c81800a5422e5fdb43533fa838b4779.jpg",
            "http://f.hiphotos.baidu.com/image/pic/item/09fa513d269759ee50f1971ab6fb43166c22dfba.jpg"
    };

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_tab, container, false);
        initViews(view);
        return view;
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

    }

    @Override
    public void onResume() {
        super.onResume();
        vp_tablayout_banner.startTurning(5000);
    }

    private void initViews(View v) {
        imgDatas = Arrays.asList(images);
        vp_tablayout_banner = (ConvenientBanner) v.findViewById(R.id.vp_tablayout_banner);
        //rv_tablayout_rv = (RecyclerView) v.findViewById(R.id.rv_tablayout_rv);

        //初始化banner
        vp_tablayout_banner.setPages(
                new CBViewHolderCreator<LocalImageHolderView>() {
                    @Override
                    public LocalImageHolderView createHolder() {
                        return new LocalImageHolderView();
                    }
                }, imgDatas);
        vp_tablayout_banner.setPageIndicator(new int[]{R.mipmap.ic_page_indicator, R.mipmap.ic_page_indicator_focused})
                .setOnItemClickListener(this);

    }

    //banner的点击事件
    @Override
    public void onItemClick(int position) {

    }

    //ConvenientBanner's Holder
    class LocalImageHolderView implements Holder<String>{

        private ImageView imageView;
        @Override
        public View createView(Context context) {
            imageView = new ImageView(context);
            imageView.setScaleType(ImageView.ScaleType.FIT_XY);
            return imageView;
        }

        @Override
        public void UpdateUI(Context context, int position, String data) {

            //imageView.setImageURI(Uri.parse(data));
            Glide.with(MyApplication.getContext())
                    .load(data)
                    .error(R.mipmap.fw1)
                    .centerCrop()
                    .into(imageView);
        }
    }
}

**Comment by saiwu-bigkoo** [comment]
目测是对的。。。

**Comment by jesse920524** [comment]
是我没加网络权限.....代码没问题!!
