### ISSUE TITLE
请教,如何为recyclerView.header的ConvenientBanner添加说明文字?

### ISSUE THREAD

**Issue by jesse920524** [saiwu-bigkoo/Android-ConvenientBanner#155]
![588139951](https://cloud.githubusercontent.com/assets/17559493/17996582/6274f8cc-6b9c-11e6-8abe-1c7b815c8b26.jpg)
我按照demo实现了ConvenientBanner作为RecyclerView的header,可如果我想在header中引入一个布局,该布局用FrameLayout包含ConvenientBanner和textView(作为图片说明文字),该如何实现??
哪位大神提供下思路??感谢!!

**Comment by saiwu-bigkoo** [comment]
作为RecyclerView的Item 第一行即可
