### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by duckAndroid** [saiwu-bigkoo/Android-ConvenientBanner#156]
我的Holder 如下：
`public class BannerHolder implements Holder<View> {

    private ImageView img;
    private LinearLayout layout;
    private LinearLayout.LayoutParams params;

    @Override
    public View createView(Context context) {
        layout = new LinearLayout(context);
        params = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT);
        return layout;
    }

    @Override
    public void UpdateUI(Context context, int position, View data) {
        layout.removeView(data);
        LogUtils.e("layout===" + layout.hashCode());
        LogUtils.e("child count===" + layout.getChildCount());
//        layout.addView();
        layout.addView(data, params);
    }

}`

来回滚动必现异常： `java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

**Comment by duckAndroid** [comment]
暂时的解决方案：在 `UpdateUi()`方法中添加
` ViewParent parent = data.getParent();
        if (parent instanceof ViewGroup) {
            ViewGroup vg = (ViewGroup) parent;
            vg.removeAllViews(); // getview 中没有做这一步操作。
        }`
=========
正确的做法是在lib中的`getView()`方法中，首先调用`container.removeAllViews();`方法。希望作者能尽快修复该bug

**Comment by saiwu-bigkoo** [comment]
public void UpdateUI(Context context, int position, View data)  你这个 View data 用法错误， data 应该是 Model 而不是View ，请看例子。
