### ISSUE TITLE
复杂界面如何不用View 作为data?

### ISSUE THREAD

**Issue by duckAndroid** [saiwu-bigkoo/Android-ConvenientBanner#157]
- 复杂的界面，比如 01 view  有两个按钮，一个图片；02 view 有一个按钮，一个进度条，两个输入框， 03 view 有 3个按钮，3个图片等.....
  ....请问这样子的bannner 如何不使用view作为data，求指导
- 在每次添加新view之前移除其他的view绝对是一个好习惯。

**Comment by saiwu-bigkoo** [comment]
那你自己在 upDateUI 里面 data.removeParent 也是可以达到同样效果。
