### ISSUE TITLE
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 900 Pager id: com.xy.skinspecialist:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter

### ISSUE THREAD

**Issue by zhangcf2012** [saiwu-bigkoo/Android-ConvenientBanner#158]
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 900 Pager id: com.xy.skinspecialist:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter

**Comment by 15806905685** [comment]
I have same question bug I can't resolve it. Could you tell me your way?
