### ISSUE TITLE
如何实现notifyDataSetChanged

### ISSUE THREAD

**Issue by liucong-albert** [saiwu-bigkoo/Android-ConvenientBanner#159]
我试过更改  banner.setPages(myCVpage,LocImgData)中的LocImgData的数据，但是发现notifyDataSetChanged执行后并没有改变我转动的图片，请教一下怎么解决？

**Comment by saiwu-bigkoo** [comment]
view pager原本就不建议notify，你要支持的话你可以看其他人拓展实现，这个 https://github.com/BinarySatan/Android-ConvenientBanner
