### ISSUE TITLE
添加下拉刷新之后，不能自动滑动

### ISSUE THREAD

**Issue by zhumingming** [saiwu-bigkoo/Android-ConvenientBanner#16]
作为listview 的header 之后，给listview 添加下拉刷新，当触摸banner下拉刷新，刷新完成后，banner不能自己滚动。希望修复，谢谢！

**Comment by tanranran** [comment]
我的解决方案是刷新完毕调用一次 convenientBanner.startTurning(BaseConfig.BannerTurningTime);

**Comment by zhumingming** [comment]
已经加上了，可是还是时好，时坏，希望修复！！！

**Comment by saiwu-bigkoo** [comment]
不好意思，是我思维不够缜密，这个BUG是因为手指超出控件没有做判断启动滑动定时器所致，下一个版本会修复，到时请看readme的更新说明
