### ISSUE TITLE
指示器问题

### ISSUE THREAD

**Issue by yuzhentao** [saiwu-bigkoo/Android-ConvenientBanner#160]
建议圆点可以水平居中对齐，不然设置不同大小的圆点时，会发现都是顶部对齐，超级丑

**Comment by saiwu-bigkoo** [comment]
你可以不用自带的圆点，自己写一个自定义的，根据翻页Listener进行联动即可

**Comment by yuzhentao** [comment]
说的也是，现在我的做法是保持不同大小的圆点一样的高度，比较蠢，但是完美解决了这个问题。
