### ISSUE TITLE
一开始还是白屏 需要手动滑动一下才会显示图片

### ISSUE THREAD

**Issue by huweijian5** [saiwu-bigkoo/Android-ConvenientBanner#162]
一开始还是白屏 需要手动滑动一下才会显示图片

**Comment by maxZhou7** [comment]
@saiwu-bigkoo 
同样遇到这样问题，求解决方案！！！

**Comment by guogailee** [comment]
貌似 ，是有这个问题存在 @saiwu-bigkoo

**Comment by kanbin** [comment]
确实，一开始白屏几秒，一滑立即出现 @saiwu-bigkoo

**Comment by kanbin** [comment]
我知道了，先设置空数据，请求下来数据再刷新就会这样，必须等请求完数据再设置

**Comment by CongZ-github** [comment]
@kanbin 按照你的提示确实解决了

**Comment by nb312** [comment]
怎么解决的

**Comment by CongZ-github** [comment]
@nb312  就是先拿到数据再设置轮播图啊

**Comment by nb312** [comment]
@CongZ-github  设置轮播图 包括初始化吗 我现在是先初始化 ，然后notif

- 初始化 
`  mConvenientBanner = (GQConvenientBanner) view.findViewById(R.id.convenientBanner);
        mConvenientBanner.setPages(new CBViewHolderCreator<IndexBannerHolderView>() {
            @Override
            public IndexBannerHolderView createHolder() {
                return new IndexBannerHolderView();
            }
        }, mNewsBeen);
`
- 更新
` 
Adapter.notifyDataSetChanged()
`

**Comment by CongZ-github** [comment]
@nb312 初始化的时候别调用mConvenientBanner.setPages
再你获取到数据的时候再调mConvenientBanner.setPages不要通过Adapter.notifyDataSetChanged()来更新

**Comment by nb312** [comment]
# 非常谢谢 已经好了 
- 数据请求成功后才只想下面的语句
`
mConvenientBanner.setPages
`

**Comment by nb312** [comment]
# @CongZ-github  非常谢谢

**Comment by xingling1122** [comment]
感谢
