### ISSUE TITLE
是否可以支持这种样式

### ISSUE THREAD

**Issue by pangli** [saiwu-bigkoo/Android-ConvenientBanner#164]
![image](https://cloud.githubusercontent.com/assets/7498978/18335959/0860e430-75b6-11e6-937c-624f1d110c1e.png)
是否可以支持这种样式

**Comment by saiwu-bigkoo** [comment]
不支持，你可以看https://github.com/DevLight-Mobile-Agency/InfiniteCycleViewPager

**Comment by pangli** [comment]
因为我们做的是平板应用，所以要实现上面的功能
1.我在你的ConvenientBanner.java中的第87行和88行加入了
       viewPager.setClipToPadding(false);
        int itemWidth = (int) getResources().getDimension(R.dimen.recommend_banner_item_width);
        int itemPading = (int) getResources().getDimension(R.dimen.recommend_banner_item_padding);
        DisplayMetrics dm = getResources().getDisplayMetrics();
        int pading = ((dm.widthPixels - itemWidth) >> 1) - itemPading;
        viewPager.setPadding(pading, 0, pading, 0);
2.在CBLoopViewPager.java中将第61行修改为
         int position = getRealItem();
         if (newX < getPaddingLeft()) {
                     position -= 1;
                    if (position < 0) {
                                             position = mAdapter.getRealCount() - 1;
                                             }
              } else if (newX > getWidth() - getPaddingRight()) {
                                position += 1;
                                if (position > mAdapter.getRealCount() - 1) {
                                    position = 0;
                                }
                            }
             onItemClickListener.onItemClick(position);
是实现了此功能。
但是有一个问题就是使用默认动画是没问题的，使用别的动画的时候就出现问题了，如果有时间你可以尝试一下，看看效果

**Comment by saiwu-bigkoo** [comment]
配合动画之后会有很严重白屏问题。所以我把动画效果移除集成也不建议使用。
