### ISSUE TITLE
Demo下gradle编译错误

### ISSUE THREAD

**Issue by newbeeeeeeeee** [saiwu-bigkoo/Android-ConvenientBanner#165]
No service of type Factory available in ProjectScopeServices.

google说as新版本2.1.3下maven的问题:classpath 'com.github.dcendents:android-maven-plugin:1.2'

版本改了还是编译不过

**Comment by saiwu-bigkoo** [comment]
你把classpath 'com.github.dcendents:android-maven-plugin:1.2' 删了也行

**Comment by newbeeeeeeeee** [comment]
可以运行了，谢谢！
