### ISSUE TITLE
图片无缓冲问题

### ISSUE THREAD

**Issue by zhangyawentudi** [saiwu-bigkoo/Android-ConvenientBanner#168]
框架真心强大，效果也很炫，但是有一个问题就是，我每次滑动一次图片会先显示默认图片，然后再加载请求到的图片，，滑动快一点就都是显示默认图片了，请求到的图片还来不及加载，就算图片全部加载完毕，我一断网，再滑动就全部显示默认图片了，这个应该算是一个比较明显的bug吧

**Comment by zhangyawentudi** [comment]
那个图片请求框架Universal-Image-Loader中的ImageLoaderConfiguration只能缓存一张图片？我有四张图片，轮播图来回切换每次都会重新加载

**Comment by zhangyawentudi** [comment]
已经解决，图片联网框架改为xUtils

**Comment by saiwu-bigkoo** [comment]
会不会是你的UIL 设置了不缓存。。。

**Comment by zhangyawentudi** [comment]
设置了UIL，但是一直无效，和缓存有关的设置你在框架里面已经设置了，是不是UIL只能缓存一张图片？

**Comment by saiwu-bigkoo** [comment]
肯定不止一张，而且还有本地缓存，你没设置好而已

**Comment by zhangyawentudi** [comment]
应该是我的问题，虽然问题没解决，因为该框架是针对轮播图，博主是否可以适当更新一下，添加轮播图的图片缓存，市面上涉及到轮播图的App都做了缓存，同时ViewPager中的setOnPageChangeListener()方法已过时，可替换为addOnPageChangeListener()
