### ISSUE TITLE
切换到其它页面，再切换回来ConvenientBanner的页面，刚好是轮播第一张图片的时候就会出现空白，然后又正常显示

### ISSUE THREAD

**Issue by OVERSKY2003** [saiwu-bigkoo/Android-ConvenientBanner#17]
ConvenientBanner在页面是作为RecyclerView的一个item存在的。

![image](https://cloud.githubusercontent.com/assets/4005701/9866594/abcb8fb6-5b96-11e5-8534-6dd5b4567e1e.png)

**Comment by liang530** [comment]
我也遇到了，特别是下拉刷新之后，是调用convenientBanner.notifyDataSetChanged();刷新会出现这种情况！

**Comment by saiwu-bigkoo** [comment]
空白的问题现已解决
