### ISSUE TITLE
不能代码里动态设置ConvenientBanner高度

### ISSUE THREAD

**Issue by wei3** [saiwu-bigkoo/Android-ConvenientBanner#171]
xml      android:layout_height="wrap_content" 然后代码里根据手机屏幕动态设置banner 高度时，会先出现banner 的PageIndicator 把页面整个占满了，请问有好的解决办法吗，毕竟每个手机的屏幕宽度是变化的，总不能在xml 写死一个高度吧，谢谢

**Comment by wei3** [comment]
补充 ···
之前我在CustomSwipeToRefresh 还嵌套了scrollview 时候代码里设置高度是没有出现这个问题的，后来因为整个布局需要用到权重，就去掉最后的scrollView ，然后就出现此上面的问题了

**Comment by saiwu-bigkoo** [comment]
无法根据内容来确定高度，只能写死dip。或者你可以用百分比布局试试。

**Comment by wei3** [comment]
已通过此方法解决我的需求 ------
   WindowManager wm = (WindowManager) mActivity.getSystemService(Context.WINDOW_SERVICE);
        // 屏幕的宽度
        int width = wm.getDefaultDisplay().getWidth();
        final int bannerHeight = (int) (width / 1.92f);
        convenientBanner.getLayoutParams().height = bannerHeight;
        convenientBanner.getLayoutParams().width = width;
        convenientBanner.requestLayout();
