### ISSUE TITLE
刷新一下，这个轮播图的切换速度越来越快，而且内存泄漏严重，这样的控件还有这么多人用，真的是有点奇葩了。

### ISSUE THREAD

**Issue by pjh520** [saiwu-bigkoo/Android-ConvenientBanner#180]

**Comment by MIkeeJY** [comment]
已经弃用了 推荐 https://github.com/youth5201314/banner 这个还是比较完善的

**Comment by qssq** [comment]
都是坑，这种东西还是简单用自己的viewpger加handler之类的实现就好了除了炫酷的效果做不到 滚动还是可以的。

**Comment by lijunhuayc** [comment]
@qssq  用这个 com.youth.banner:banner:1.4.2

**Comment by lijunhuayc** [comment]
@qssq 额，楼上有人已经发了链接了  https://github.com/youth5201314/banner

**Comment by ganshenml** [comment]
@MIkeeJY @lijunhuayc 那个也是有问题的，在部分机型上面会出现轮播回到第一页的时候图片被莫名上下拉伸，没人解决。

**Comment by MIkeeJY** [comment]
@ganshenml https://github.com/jinloong/BannerLayout  如果只有轮播功能的话 这个绝对能满足你。。。bug也很少

**Comment by ganshenml** [comment]
@MIkeeJy 嗯，目前暂时只用到这个
