### ISSUE TITLE
scroolView  嵌套 自动下滑

### ISSUE THREAD

**Issue by wasneverlonely** [saiwu-bigkoo/Android-ConvenientBanner#184]
我使用scroolView 嵌套  滑到下面的时候  轮播图  切换的时候自动上滑到顶部

**Comment by caofei0** [comment]
这不是为我的项目，你去找以前写项目的哪个人问吧

在 2016-11-17 09:54:48，"wasneverlonely" <notifications@github.com> 写道：


我使用scroolView 嵌套 滑到下面的时候 轮播图 切换的时候自动上滑到顶部

**Comment by getpro** [comment]
我也遇到这个bug了,,嵌套在scrollview里面会自动滑动到顶部，有没有解决？

**Comment by getpro** [comment]
@saiwu-bigkoo scrollview嵌套的bug怎么解决？

**Comment by xinyang123123** [comment]
我也遇到了
