### ISSUE TITLE
 app:canLoop="false" //控制循环与否，会有内存泄露的严重bug

### ISSUE THREAD

**Issue by xueyaolive** [saiwu-bigkoo/Android-ConvenientBanner#187]
当你的图片刚好只有一张，或者没有时，你调用了 convenientBanner.notifyDataSetChanged();就会出现死循环，只能设置为true，

**Comment by caofei0** [comment]
这不是我的moudel，你去问写的人吧，我不知道你们怎么晓得我的邮箱

在 2016-11-22 10:14:10，"xueyaolive" <notifications@github.com> 写道：


当你的图片刚好只有一张，或者没有时，你调用了 convenientBanner.notifyDataSetChanged();就会出现死循环，只能设置为true，
