### ISSUE TITLE
除了Image還想加入字串或其他view

### ISSUE THREAD

**Issue by Arthas-Fung** [saiwu-bigkoo/Android-ConvenientBanner#19]
convenientBanner.setPages(new CBViewHolderCreator<ImageHolder>() {
            @Override
            public ImageHolder createHolder() {
                return new ImageHolder();
            }
        },networkImages);

networkImages 只能是List<String>
不能用
ArrayList<HashMap<String,Object>> 這類 ?  
"image"  : url
"text" : "hello this is image 1" 
然後在相片上顯示字串

**Comment by saiwu-bigkoo** [comment]
Hello，是可以的，你用List声明 ＝ ArrayList ，然后add 新的Item，notifydatachange就行，在相片上显示字符串的话，参考demo，demo是一个image，你可以增加textview的
