### ISSUE TITLE
指示器设置后不显示

### ISSUE THREAD

**Issue by lvjunling** [saiwu-bigkoo/Android-ConvenientBanner#20]
holder.convenientBanner.setPageIndicator(new int[]{R.drawable.kw_homesys_dotnormal, R.drawable.kw_homesys_dotselected});
        holder.convenientBanner.setPageIndicatorAlign(ConvenientBanner.PageIndicatorAlign.ALIGN_PARENT_RIGHT);
        holder.convenientBanner.setPages(new CBViewHolderCreator<NetworkImageHolderView>() {
            @Override
            public NetworkImageHolderView createHolder() {
                return new NetworkImageHolderView();
            }
        }, images);

**Comment by saiwu-bigkoo** [comment]
你好，demo里面指示器测试过是可以显示的，你对比一下哪里问题
