### ISSUE TITLE
找不到Transformer.DefaultTransformer这个变量

### ISSUE THREAD

**Issue by Luckychuan** [saiwu-bigkoo/Android-ConvenientBanner#203]
找不到Transformer.DefaultTransformer这个变量
有没有默认的PageIndicator
没有默认的高度吗？wrap content没用

**Comment by zhongzhihuashanghai** [comment]
这是一个开源的pager翻页效果，https://github.com/ToxicBakery/ViewPagerTransforms，你查看这个，然后在gradle中关联compile 'com.ToxicBakery.viewpager.transforms:view-pager-transforms:1.2.32@aar'就可以了，有很多很炫的效果
