### ISSUE TITLE
控件缓存没啥用啊，每次都会创建新的，为啥这么用ViewHolder ?

### ISSUE THREAD

**Issue by huirong628** [saiwu-bigkoo/Android-ConvenientBanner#206]

**Comment by 77jiang** [comment]
是的，这一部分逻辑有问题
instantiateItem中写到View view = getView(realPosition, null, container);
然而getView中写到
public View getView(int position, View view, ViewGroup container) {
        Holder holder = null;
        if (view == null) {
            holder = (Holder) holderCreator.createHolder();
            view = holder.createView(container.getContext());
            view.setTag(R.id.cb_item_tag, holder);
        } else {
            holder = (Holder<T>) view.getTag(R.id.cb_item_tag);
        }
        if (mDatas != null && !mDatas.isEmpty())
            holder.UpdateUI(container.getContext(), position, mDatas.get(position));
        return view;
    }
view每次都给空。那每次都会创建，还判断什么？

**Comment by nanchen2251** [comment]
同问，这样根本不能记住状态

**Comment by willfan001** [comment]
这样反复创建View还是不妥的，得把CBPageAdapter里面的destroyItem里面removeView掉View，回收利用起来才行，我改了下大致这样。
private View mRecyclingView;
 @Override
    public Object instantiateItem(ViewGroup container, int position) {
        int realPosition = toRealPosition(position);
        View view = getView(realPosition, mRecyclingView, container);
        container.addView(view);
        mRecyclingView = null；
        return view;
    }

    @Override
    public void destroyItem(ViewGroup container, int position, Object object) {
        View view = (View) object;
        container.removeView(view);
        mRecyclingView = view;
    }
