### ISSUE TITLE
下拉刷新之后，有时候滑动会失效，convenientBanner.notifyDataSetChanged();之后，第一张图会变空白！

### ISSUE THREAD

**Issue by liang530** [saiwu-bigkoo/Android-ConvenientBanner#21]

**Comment by saiwu-bigkoo** [comment]
v1.1.0+ 的版本修复了空白问题，你更新最新版试试看

**Comment by liang530** [comment]
非常感谢，这段时间比较忙，没注意动态，不好意思，我有时间就去试试！




------------------ 原始邮件 ------------------
发件人: "sai";<notifications@github.com>;
发送时间: 2015年11月9日(星期一) 晚上6:13
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 
抄送: "泡∝影→……"<752284118@qq.com>; 
主题: Re: [Android-ConvenientBanner] 下拉刷新之后，有时候滑动会失效，convenientBanner.notifyDataSetChanged();之后，第一张图会变空白！ (#21)




v1.1.0+ 的版本修复了空白问题，你更新最新版试试看
