### ISSUE TITLE
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged!

### ISSUE THREAD

**Issue by weather2rain** [saiwu-bigkoo/Android-ConvenientBanner#214]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 600, found: 0 Pager id: com.xyzq.pbank:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter
请教一下，这个异常怎么处理，我多次切换fragment就会崩溃

**Comment by summerwang1** [comment]
刷新，内容的时候同会出现，求解决办法

**Comment by leafseelight** [comment]
adapter数据源和外部数据源要同步，外部数据源修改的时候，要notifydatasetchange下。
