### ISSUE TITLE
给 RecyclerView  当 HeaderView 时偶尔会出现翻页翻一半卡一下的问题。

### ISSUE THREAD

**Issue by Jimmy-J** [saiwu-bigkoo/Android-ConvenientBanner#216]
1.当 RecyclerView item 数量有很多，我滑动到最底部，快速往上滑动，偶尔出现 banner 卡在两页切换中，，过一秒钟后才会正常自动翻页。

**Comment by Jimmy-J** [comment]
有解决思路吗

**Comment by i-show** [comment]
虽然这个库我已经好久不用了，但是你这种情况应该是获取焦点的时候就滚动一屏 就可以解决

**Comment by Jimmy-J** [comment]
我现在使用了 RecyclerVIew 来编写banner，也存在在这个问题，但是在 onWindowVisibilityChanged 不可见时调用 scrollToPosition 滑动到一个屏幕就解决了
