### ISSUE TITLE
默认显示问题，手动滑动后自动滚动图片问题

### ISSUE THREAD

**Issue by blazecake** [saiwu-bigkoo/Android-ConvenientBanner#225]
![gif截屏图片](https://user-images.githubusercontent.com/6480101/33227190-8a85c578-d1d8-11e7-8c3c-ac00b63f5e8c.gif)

在如下情况下：
显示两张图片
app:canLoop="false"
stopTurning()

问题：
1、默认显示第二张图片
2、滑动到第一张图片后，banner自动滑动到第二张图片

**Comment by Learzhu** [comment]
我也遇到了这个问题 默认一直显示最后一张 请问在 2.1.4解决了吗？
