### ISSUE TITLE
如何停止循環?

### ISSUE THREAD

**Issue by Arthas-Fung** [saiwu-bigkoo/Android-ConvenientBanner#23]
在最後1頁不能向右掃回第1頁 及 第1頁不能向左掃到最後頁

還有另1問題就是在activity第一次增加圖片在ConvenientBanner上,然後向左掃就加載失敗.再次掃左或右才回復正常

**Comment by saiwu-bigkoo** [comment]
停止循环问题：你可以判断只有一页就禁止滑动，有提供相关api。
对于第一次左扫失败这个bug确实存在，目前还没有修复，非常抱歉。

**Comment by Arthas-Fung** [comment]
感謝回答, 因為我在做 第1次開app時的教學,是圖片的 有數頁,最後1頁有個確定制去首頁, 所以想禁止別人向左掃

**Comment by saiwu-bigkoo** [comment]
这个需求比较特殊，目前没有支持，你可以自己通过拦截事件传递拓展一下
