### ISSUE TITLE
使用kotlin 出现编译错误

### ISSUE THREAD

**Issue by imxy** [saiwu-bigkoo/Android-ConvenientBanner#230]
![ld_ k 0h3_9 2h z a3](https://user-images.githubusercontent.com/20613737/34943653-782dd4f6-fa37-11e7-93d7-5137ce45db31.png)
如图。。。

**Comment by imxy** [comment]
![a28pljrlfm5i 60 jps6 s](https://user-images.githubusercontent.com/20613737/35024591-5237cb18-fb7b-11e7-90a7-6001f5639c19.png)
已解决，是泛型的问题

**Comment by 944095635** [comment]
用起来好复杂啊。我也遇到这个问题了。用java 专程 kotlin  语法 都有问题

**Comment by imxy** [comment]
@944095635 不复杂吧，只是kotlin必须要指明类型才行，强制转换下就好了

**Comment by Code6666** [comment]
kotlin必须要指明类型才行，强制转换下就好了 
 (mConvenientBanner  as  ConvenientBanner<String>)!!.setPages(object : CBViewHolderCreator {
            override fun createHolder(itemView: View?): Holder<*> {
                return BannerImageHolder(itemView)
            }

            override fun getLayoutId(): Int {
                return R.layout.item_main_home_banner_image
            }
        },bannerImageList)

**Comment by Code6666** [comment]
kotlin必须要指明类型才行，强制转换下就好了

(mConvenientBanner as ConvenientBanner)!!.setPages(object : CBViewHolderCreator {
override fun createHolder(itemView: View?): Holder<*> {
return BannerImageHolder(itemView)
}
override fun getLayoutId(): Int {
            return R.layout.item_main_home_banner_image
        }
    },bannerImageList)
