### ISSUE TITLE
自动测试发现一个bug

### ISSUE THREAD

**Issue by utfqvfhpyygy** [saiwu-bigkoo/Android-ConvenientBanner#25]
![dc5addad-2696-46e7-8e43-0f5ed751f122](https://cloud.githubusercontent.com/assets/223516/10662023/201fb54e-78e4-11e5-8048-6e853197c458.jpg)

**Comment by saiwu-bigkoo** [comment]
fix

**Comment by utfqvfhpyygy** [comment]
可以更新 gradle 依赖版本吗

**Comment by saiwu-bigkoo** [comment]
hello，已更新
