### ISSUE TITLE
如何正常显示圆角

### ISSUE THREAD

**Issue by SunxiaoyaoHHL** [saiwu-bigkoo/Android-ConvenientBanner#269]
请问一下，设置了圆角，滑动时又变了成直角，怎么解决呢

**Comment by saiwu-bigkoo** [comment]
请问你的圆角设在哪

**Comment by SunxiaoyaoHHL** [comment]
banner的background还有iamgeview都设了圆角，如果只有滑动过程中会变成直角

**Comment by wmhqnyh** [comment]
@SunxiaoyaoHHL Hello，麻烦问下现在你的这个圆角解决了吗？我用到作者的库之后也是这个问题。

**Comment by troyccc** [comment]
控件 嵌套在cardview 里面就好了
