### ISSUE TITLE
棉花糖系统有问题

### ISSUE THREAD

**Issue by brucewuu520** [saiwu-bigkoo/Android-ConvenientBanner#27]
我的手机是nexus5，6.0系统，连续快速滑动时，ui会卡顿大约5秒的时间，卡的不能进行任何操作，也没报错，5秒后正常，查阅了下源码也没找出是什么原因

**Comment by saiwu-bigkoo** [comment]
会不会是其他原因，比如你使用的网络下载图片时候造成？

**Comment by brucewuu520** [comment]
不会的有缓存的，而且即使是网络不好，最多是图片加载不出来，ui不会卡顿吧，会卡的整个界面不能动

**Comment by saiwu-bigkoo** [comment]
同样的代码你试试用其他版本系统跑跑看有没问题

**Comment by brucewuu520** [comment]
其他版5.0，4.4都试过了还真没有问题，就是6.0有问题

**Comment by saiwu-bigkoo** [comment]
请试试最新版看看是否还存在此问题

**Comment by brucewuu520** [comment]
欧了。谢谢
