### ISSUE TITLE
ConvenientBanner放在RecyclerView.Adapter里面，刷新页面，会出现滚动的空白页

### ISSUE THREAD

**Issue by OVERSKY2003** [saiwu-bigkoo/Android-ConvenientBanner#3]
![image](https://cloud.githubusercontent.com/assets/4005701/9221054/c2073e84-4119-11e5-9683-c4bf35d12377.png)

**Comment by saiwu-bigkoo** [comment]
请问你是怎么刷新的？刷新的时候做了什么操作？能具体说明下吗？

**Comment by OVERSKY2003** [comment]
在onBindViewHolder调用initBanner初始化banner.  刷新数据时是mAdapter.notifyDataSetChanged();
  @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {

        if (getItemViewType(position) == ViewTypeBanner) {
            BannerViewHolder bannerViewHolder = (BannerViewHolder) viewHolder;
            mViewPager = bannerViewHolder.bannerViewPager;
            if (imageURLs != null && imageURLs.size() > 0) {
                mViewPager.setVisibility(View.VISIBLE);
                initBanner();
            } else {
                mViewPager.setVisibility(View.GONE);
            }


        }
}
 
   private void initBanner() {
        if (!isBannerInit) {
            isBannerInit = true;
        } else {
            return;
        }

        mViewPager.setPages(new CBViewHolderCreator<NetworkImageHolderView>() {
            @Override
            public NetworkImageHolderView createHolder() {
                return new NetworkImageHolderView();
            }
        }, imageURLs);

        if(imageURLs.size() <= 1){
            mViewPager.stopTurning();
        }else{
            mViewPager.startTurning(5000);//每5秒
            mViewPager.setPageIndicator(new int[]{R.drawable.banner_indicator, R.drawable.banner_indicator_focused});
        }



    }

    public class NetworkImageHolderView implements CBPageAdapter.Holder<String>{
        private ImageView imageView;
        @Override
        public View createView(Context context) {
            imageView = new ImageView(context);
            imageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
            return imageView;
        }

        @Override
        public void UpdateUI(Context context, final int position, String data) {
            bitmapUtils.display(imageView, data);
            imageView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {

                }
            });
        }

**Comment by saiwu-bigkoo** [comment]
我自己写了个demo测试，没有你说的问题。请下载最新的demo参考，源码在recyclerviewdemo 的package下面
