### ISSUE TITLE
当设置滚动间为1000毫秒时，滚动异常

### ISSUE THREAD

**Issue by HenseyVenom** [saiwu-bigkoo/Android-ConvenientBanner#34]
当设置startTurning(1000)的时候，我使用了三张图片，第一圈滚动是正常的从左往右滚动，但是当滚动进行到第二圈的时候，到第二张图片的时候是从右向左滚动，然后在从左向右滚动，往后每一圈的顺序都是这样的，但是设置startTurning(2000)的时候是正常的

**Comment by saiwu-bigkoo** [comment]
我测试了下，确实是有这样的问题。因为无限循环就是 增加了最后一个View(跟index 为 0 一摸一样的View) ，其实是从 最后一个View 切到 0 View看起来是无限循环，而这个问题出现是因为 1000的话，还没那么快能切到0View，直接从了最后一个View切到1View去了，看起来就会从右直接翻到左1View去。对于这个问题我也暂时无解了。如果硬要支持1000以内的话，可以修改ViewPagerScroller里面的mScrollDuration，但同时如果用到3d效果的话3d效果的展示就会不明显了。
