### ISSUE TITLE
ViewPager在滑动的时候有点不流畅

### ISSUE THREAD

**Issue by imliujun** [saiwu-bigkoo/Android-ConvenientBanner#35]
关于ViewPage使用硬件layers的一些问题
http://blog.udinic.com/2013/09/16/viewpager-and-hardware-acceleration

ConvenientBanner没有ViewPage暴露出来，并且也没有提供OnPageChangeListener方法。希望能够改进这一块，因为快速滑动的时候确实会卡顿

**Comment by saiwu-bigkoo** [comment]
你好，我尝试你发的网址介绍的方法，但效果也没有差别。OnPageChangeListener没开放出来确实是疏忽了，多谢提醒，下一个版本会开放出来。
