### ISSUE TITLE
高度设置为wrap_content无效

### ISSUE THREAD

**Issue by pickyourself** [saiwu-bigkoo/Android-ConvenientBanner#36]
listView设置为头部视图时，设置banner的高度为wrap_content 无效，必须要设置固定高度或match_parent， 另外，源码里好像没有重新测算高度

**Comment by saiwu-bigkoo** [comment]
请问应该怎么计算高度好呢？我没有好的idea来解决这个问题，如果你有麻烦提点下。

**Comment by pickyourself** [comment]
我觉得重写onMesure()方法可以的。模式为 MeasureSpec.AT_MOST;

**Comment by saiwu-bigkoo** [comment]
不行，特别是使用网络图片的时候。
