### ISSUE TITLE
请问一下如何动态更新图片资源

### ISSUE THREAD

**Issue by ChineseLincoln** [saiwu-bigkoo/Android-ConvenientBanner#38]
我这边有个项目，其中的广告图是根据商场不同需要切换不同的广告图。
List中存放的是DrawableId，然后clean了List数据后，重新向List内add了新的DrawableId。然后调用调用notifyDataSetChange，控件不刷新生效，只能重新setPage才能生效
请问一下是我哪个地方做错了嘛？

**Comment by saiwu-bigkoo** [comment]
对于这个更新我也是很无奈，viewpager原本就不刷新，所以不建议重新设置新数据，应该从一开始就设置好正确的数据，不然也就只能重新setAdapter了。
