### ISSUE TITLE
会有空白页

### ISSUE THREAD

**Issue by hetianpeng** [saiwu-bigkoo/Android-ConvenientBanner#41]
最后一个轮播到达第一个时会有。

**Comment by saiwu-bigkoo** [comment]
请问你的当前版本是多少呢？这个BUG我处理过，最新版应该是解决了的。

**Comment by hetianpeng** [comment]
1.1.2我刚更新的，还是会有，我是在RecyclerView.Adapter中用到的。

**Comment by saiwu-bigkoo** [comment]
我测试了下，空白页问题确实存在，但几率很小，你可以用demo里面的ADRecyclerViewDemo的方式addHeader试试。

**Comment by Gaara33** [comment]
NetworkImageHolderView在这个类中，我设置了加载网络图片，滑动到第一页的时候，在滑动第二页之前的间隙，会有空白，因为我设置了默认图片，就会显示默认图片，图片有的没加载完成时会出现，图片全部加载完成后，也会出现一小会儿，然后又会恢复正常，清理缓存再运行，还是有此种情况发生，魅族手机很少出现，1加手机出现的频率很大

**Comment by saiwu-bigkoo** [comment]
楼上的这个空白是下载图片慢的问题吧？

**Comment by Gaara33** [comment]
我几天更新了最新的版本,和之前相比,NetworkImageHolderView中updateui可以用imageloader时,imageloader自带的tag机制和以前的tag不再冲突了,adapter中的tag增加了id,出现空白的时候是网络慢些,下载图片慢,但是举个例子,banner上要加载两页图片,这两页图片已经看到加载完成了,因为都看到效果了,但是在第一页滑到第二页之前,会有短暂的空白,这时候点击,点击事件在第一张图片上(经过验证),这种情况有时候很快就恢复正常了,有时候会持续好几轮循环都有...

**Comment by Gaara33** [comment]
因为这是测试测出来的bug,在网络好的时候,很难出现,就特意选了网络差的时候,每次运行完,清除缓存,再次运行,
如果图片没有加载出来显示底图我们认为这是正常现象,但是已经看到了需要加载的图片,还是会出现空白闪烁,出现的时间具体在滑动到最后再到第一页的时候,第一页的图片刚刚完全平铺显示,立即变为默认的底图,然后以正常的速度滑动到第二页,

**Comment by Gaara33** [comment]
imageView.postDelayed(new Runnable() {
			@Override
			public void run() {
				ImageUtils.requestImage(imageView,data.getmTagsrc(),DisplayUtils.getWidthPixels(),BANNER_HEIGHT, R.drawable.banner_default);
			}
		}, 500);

我在网络加载图片时,延时了半秒钟,在网络比较差的情况下,目前还没有出现上述bug,如果此后再出现,再来分享沟通..

**Comment by hetianpeng** [comment]
sorry，这几天在医院。我加载的是本地图片，这空白也出现的方式是，当将banner往上滑动至屏幕之外，然后再往下滑动至出现，反复几次，就会看见空白页。

**Comment by a740169405** [comment]
很不幸我的也出现了空白页

**Comment by Gaara33** [comment]
没关系的,我们本来就是在交流问题,有事的话先办事,祝福大家平安健康.

**Comment by Gaara33** [comment]
呃.........好吧,我往上翻了翻,看错了,以为是楼主呢,万恶的默认头像,呵呵呵...

**Comment by saiwu-bigkoo** [comment]
新改了循环逻辑，空白页问题彻底解决
