### ISSUE TITLE
 app:canLoop="true" //控制循环与否

### ISSUE THREAD

**Issue by qluojieq** [saiwu-bigkoo/Android-ConvenientBanner#45]
这句话运行时会报错，求解
使用时android studio

**Comment by saiwu-bigkoo** [comment]
xmlns:app="http://schemas.android.com/apk/res-auto"  漏写吧

**Comment by qluojieq** [comment]
其实我就是想问，可否在代码中设置，设置方法是什么，
在xml按例子中的进行了设置，在运行时报错了，跑不起来，

**Comment by saiwu-bigkoo** [comment]
在new ConvenientBanner的时候可以设置。xml方式报错你也可以看报错提示分析下原因，肯定是支持xml方式的。

**Comment by qluojieq** [comment]
方法名字叫什么，可以告知一下吗，我查询了你们的文档并没有找到，

**Comment by saiwu-bigkoo** [comment]
ConvenientBanner的构造函数，你必须用代码new  ConvenientBanner才可以设置
