### ISSUE TITLE
图片乱跳，还会有空白页

### ISSUE THREAD

**Issue by Calamus-Cajan** [saiwu-bigkoo/Android-ConvenientBanner#48]
ConvenientBanner.setScrollDuration(10000);
ConvenientBanner.startTurning(10000);
我自定义了淡入淡出的切换效果，再做了模糊处理，有时候图片就会乱跳，还会有空白页。

**Comment by saiwu-bigkoo** [comment]
startTurning 的数值要大于 setScrollDuration的，因为还没有滚动翻页结束又开始另外一页的翻页动作了，会冲突
