### ISSUE TITLE
当与下拉刷新控件组合时，无法正常左右手动滑动

### ISSUE THREAD

**Issue by sb3h** [saiwu-bigkoo/Android-ConvenientBanner#49]
与compile 'in.srain.cube:ultra-ptr:1.0.11' 该开源插件，把Banner组合到ListView的HeaderView上，出现打侧方向下拉，就会卡住一下，然后无法正常左右手动滑动

**Comment by saiwu-bigkoo** [comment]
他有解决方案的，你找找issues看有没有人提过。这个冲突是下拉刷新控件进行处理的，我这一层解决不了。

**Comment by sb3h** [comment]
他的解决方案是这个属性吧？
让下拉刷新控件设置
mPtrFrame.disableWhenHorizontalMove(true);

**Comment by sb3h** [comment]
请问您那个如何提交代码到您的代码上面。我看您还没有解决那个黑屏的问题。
private Runnable adSwitchTask = new Runnable() {
        @Override
        public void run() {
            if (viewPager != null && turning) {
            	if (mDatas!=null) {
            		if (mDatas.size()>0) {
            			int page = (viewPager.getCurrentItem() + 1)%(mDatas.size());
                        viewPager.setCurrentItem(page);
                        timeHandler.postDelayed(adSwitchTask, autoTurningTime);
					}
            		
				}
                
            }
        }
    };
在ConvenientBanner文件的adSwitchTask加上判断就好了

**Comment by sb3h** [comment]
能加个扩展吧。
public ConvenientBanner setPageIndicator(int[] page_indicatorId) {
    	ViewGroup vg = loPageTurningPoint;
        if (getExternalLoPageTurningPoint()!=null) {
        	vg = getExternalLoPageTurningPoint();
		}
        vg.removeAllViews();
在ConvenientBanner文件上添加一个Layout，让其外部控制那个PageIndicator。谢谢
