### ISSUE TITLE
应为某种特殊情况,我可能会startTurning多次

### ISSUE THREAD

**Issue by tanranran** [saiwu-bigkoo/Android-ConvenientBanner#5]
于是会出现 轮播速度变快的情况,能否加一个判断当前是否已经正在轮播的方法 turning这个属性是private
能否改成public或者提供get方法

**Comment by saiwu-bigkoo** [comment]
hey，谢谢你的反馈。在新版本 "1.0.5" 中 修复了这个功能，并开放了 isTurning 接口。原本的 startTurning(long autoTurningTime)  接口里面我加入了 是否正在翻页的判断，如果是的话会先停止之前的翻页，然后再重新启动新的翻页。所以你不必改动现在的代码更新最新版本就可以修复此bug了。
