### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by yeagle2468** [saiwu-bigkoo/Android-ConvenientBanner#50]
1、首先很致命的问题，用起来居然卡卡的
       手指滑动过后，感觉有些滞后
2、我用在ViewPager里面嵌套，点击每个Item居然无效；
3、canLoop不能再代码里面设置。如果我实现不清楚是否需要canLoop，那么我肯定是要在后面设置的，xml文件可以，代码居然不可以

**Comment by saiwu-bigkoo** [comment]
1.新版修改了逻辑，现在不卡了。
2.我提供了setOnItemClickListener进行监听。
3.canLoop需要一开始就决定好，所以代码方式提供了ConvenientBanner(Context context,boolean canLoop) 构造函数中设置。目前还不支持想改就改。
