### ISSUE TITLE
一直往左滑 出现白屏了~

### ISSUE THREAD

**Issue by 0924chun** [saiwu-bigkoo/Android-ConvenientBanner#52]
版本2.0

**Comment by saiwu-bigkoo** [comment]
能具体描述下吗？数据变更了没？

**Comment by 0924chun** [comment]
我改成1.14就好了。。 ，往左滑会白屏 本地图片和网络图片都会

**Comment by saiwu-bigkoo** [comment]
一直往左滑是滑了一会就出现呢还是很难才出现？能否提供会白屏的demo给我测试下呢，这次我改动了逻辑，按理说不会再白屏才对。

**Comment by darin-lao** [comment]
2.0.0 一直往左滑用fresco SimpleDraweeView加载图片会出现空白

**Comment by kealsoul** [comment]
1.1.4是可以的，换成2.0就不得行了

**Comment by saiwu-bigkoo** [comment]
请试用2.0.1
