### ISSUE TITLE
发现一个新的问题

### ISSUE THREAD

**Issue by brucewuu520** [saiwu-bigkoo/Android-ConvenientBanner#56]
设置了适配器数据后，如果更新适配器数据，会有比较长的一段时间页面显示空白，之前的版本没这个问题的

**Comment by abbenyyyyyy** [comment]
请问怎么更新适配器数据啊，作者已经把notifyDataSetChanged（）注释掉了啊

**Comment by saiwu-bigkoo** [comment]
建议先用回1.1.4版本吧，2.0版本的问题目前还没时间修复。

**Comment by brucewuu520** [comment]
大概是什么原因造成了，可以说下吗？

**Comment by saiwu-bigkoo** [comment]
这个我目前也不知道

**Comment by saiwu-bigkoo** [comment]
空白页问题，我测试了是集成动画效果问题。新版本已经分离了动画效果了，请更新

**Comment by brucewuu520** [comment]
好的，谢谢，其实我也解决了，修改下适配器就好了
public class CBPageAdapter<T> extends RecyclingPagerAdapter {

    protected List<T> mDatas;
    protected CBViewHolderCreator holderCreator;
    private boolean canLoop = true;

    public CBPageAdapter(CBViewHolderCreator holderCreator) {
        this.holderCreator = holderCreator;
    }

    public CBPageAdapter(CBViewHolderCreator holderCreator, List<T> datas) {
        this.holderCreator = holderCreator;
        this.mDatas = datas;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup container) {
        Holder holder;
        if (convertView == null) {
            holder = (Holder) holderCreator.createHolder();
            convertView = holder.createView(container.getContext());
            convertView.setTag(R.id.cb_item_tag, holder);
        } else {
            holder = (Holder<T>) convertView.getTag(R.id.cb_item_tag);
        }
        holder.UpdateUI(container.getContext(), position, mDatas.get(toRealPosition(position)));
        return convertView;
    }

    public void setDatas(List<T> datas) {
        if (mDatas != null)
            mDatas.clear();
        this.mDatas = datas;
        notifyDataSetChanged();
    }

    public int toRealPosition(int position) {
        int realCount = getRealCount();
        if (realCount == 0)
            return 0;
        int realPosition = position % realCount;
        return realPosition;
    }

    @Override
    public int getCount() {
        return canLoop ? Integer.MAX_VALUE : getRealCount();
    }

    public int getRealCount() {
        return mDatas == null ? 0 : mDatas.size();
    }

    public void setCanLoop(boolean canLoop) {
        this.canLoop = canLoop;
    }

    /**
     * @param <T> 任何你指定的对象
     */
    public interface Holder<T> {
        View createView(Context context);

        void UpdateUI(Context context, int position, T data);
    }
}
