### ISSUE TITLE
我用1.1.4还是会出现空白页

### ISSUE THREAD

**Issue by androidxiaobai** [saiwu-bigkoo/Android-ConvenientBanner#59]
最后一张banner到第一张时图片第一张图片会是空白页但是点击事件什么的操作不影响。想问一下2.0.0的问题解决了吗？

**Comment by saiwu-bigkoo** [comment]
请问你的使用了动画效果吗？我发现动画效果会偶尔出现白屏，新版本中已经分离出去了，你可以试试新版本。
