### ISSUE TITLE
crash了 请问在哪里调用notifyDataSetChanged 加载的网络图片

### ISSUE THREAD

**Issue by androidxiaobai** [saiwu-bigkoo/Android-ConvenientBanner#61]
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 4, found: 2 Pager id: com.kupangstudio.shoufangbao:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.CBLoopPagerAdapterWrapper
                                                                                         java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 4, found: 2 Pager id: com.kupangstudio.shoufangbao:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.CBLoopPagerAdapterWrapper

**Comment by saiwu-bigkoo** [comment]
2.0.0版本去掉了notifyDataSetChanged，现在新版本又重新添加回去了，你可以试试。网络加载Demo中也是有例子的，注释的那部分代码。
