### ISSUE TITLE
我把ListView传入去，ListView没有填充满父布局，你认为该怎么做？

### ISSUE THREAD

**Issue by abbenyyyyyy** [saiwu-bigkoo/Android-ConvenientBanner#62]
因为项目要求轮播内容是（照片+标题）所以我采用了传入的控件是ListView，我已经调用了listView.setLayoutParams，但是据观察得到结果是listView的填充仍然是wrap_content，这问题我卡了两天，请问你知道该怎么做吗？

**Comment by saiwu-bigkoo** [comment]
（照片+标题），你完全可以隐藏了自带的 点 指示器，然后在Banner上面覆盖一层标题的View，通过onPageChange 关联来更新标题view
