### ISSUE TITLE
自动滑动时，动画效果不工作

### ISSUE THREAD

**Issue by sb3h** [saiwu-bigkoo/Android-ConvenientBanner#63]
当与GridViewWithHeaderAndFooter（https://github.com/liaohuqiu/android-GridViewWithHeaderAndFooter）组合时，该Banner作为GridView的Header，就没有起效

**Comment by saiwu-bigkoo** [comment]
试试新版本，另外能否提供下例子给我也测试下呢？

**Comment by sb3h** [comment]
https://github.com/sb3h/convenientbannerTest 这是我组合的demo，有空就把这个问题fixed了吧，谢谢！

**Comment by saiwu-bigkoo** [comment]
我试了下，确实自动滑动不行的，但这个问题不是我能fix的，应该是GridViewWithHeaderAndFooter内部问题，只能建议你使用RecyclerView的grid效果了，RecyclerView一样可以添加Header，你可以看看我demo里面的配合RecyclerView的例子，改一改变为grid样式就行了。

**Comment by sb3h** [comment]
好的。我回头试一试。谢谢你的时间
