### ISSUE TITLE
Image with TextView

### ISSUE THREAD

**Issue by lowfiend** [saiwu-bigkoo/Android-ConvenientBanner#64]
Hi

I have a question like this img
http://imgur.com/2653Itz

If I want to auto run  textview according to img 

How can I do?

**Comment by saiwu-bigkoo** [comment]
That easy to do that. You can  new a Holder like LocalImageHolderView( in demo ). You just add a LinearLayout include a image add a textview.

**Comment by saiwu-bigkoo** [comment]
public class DemoHolderView implements Holder<Object(Here you can make your Object like ImageTextObject ,that's OK)> {
private LinearLayout layout;
    private ImageView imageView;
private TextView text;
    @Override
    public View createView(Context context) {
       layout = LayoutInflater.from(context).inflate(R.layout.xxxxx);
imageview = layout.findViewById(R.id.xxx);
text = ........;
        return layout;
    }

    @Override
    public void UpdateUI(Context context, int position, Object data) {
        imageView.setImageResource(data.imageUrl);
text.setText(data.text);
    }
}

**Comment by lowfiend** [comment]
Thanks a lot.
But I use
<com.bigkoo.convenientbanner.ConvenientBanner
            android:id="@+id/convenientBanner"
            android:layout_width="150dp"
            android:layout_height="match_parent"
            android:layout_marginBottom="30dp" />

so 

ImageLoader.getInstance().displayImage(data,imageView);

imageView is error

How can I do?

**Comment by saiwu-bigkoo** [comment]
You can download the zip。Check the demo with NetworkImageHolderView.java。

**Comment by lowfiend** [comment]
I had downloaded it.

 imageView = new ImageView(context);
        main =(TextView) convertView.findViewById(R.id.main);
        desc =(TextView) convertView.findViewById(R.id.desc);
        return convertView;

But no image display.

Maybe no display question is  return convertView have no imageview?

**Comment by saiwu-bigkoo** [comment]
//网络图片例子,结合常用的图片缓存库UIL,你可以根据自己需求自己换其他网络图片库
        DisplayImageOptions defaultOptions = new DisplayImageOptions.Builder().
                showImageForEmptyUri(R.drawable.ic_default_adimage)
                .cacheInMemory(true).cacheOnDisk(true).build();

        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(
                getApplicationContext()).defaultDisplayImageOptions(defaultOptions)
                .threadPriority(Thread.NORM_PRIORITY - 2)
                .denyCacheImageMultipleSizesInMemory()
                .diskCacheFileNameGenerator(new Md5FileNameGenerator())
                .tasksProcessingOrder(QueueProcessingType.LIFO).build();
        ImageLoader.getInstance().init(config);


Were you config the ImageLoader correctly？

**Comment by saiwu-bigkoo** [comment]
Oh,No.  
  imageView = new ImageView(context);   
You must change to this:
imageView = (ImageView) convertView.findViewById(R.id.imageview);

**Comment by lowfiend** [comment]
ImageLoader  is correct.

But 

https://github.com/saiwu-bigkoo/Android-ConvenientBanner/blob/master/app/src/main/res/layout/activity_main.xml

<com.bigkoo.convenientbanner.ConvenientBanner
        android:id="@+id/convenientBanner"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:canLoop="true"/>

Here is no R.id.imageview

**Comment by saiwu-bigkoo** [comment]
god,Can I speak Chinese?

**Comment by lowfiend** [comment]
OK

**Comment by saiwu-bigkoo** [comment]
你可以通过 implements Holder 来自定义你的界面，非activity_main.xml，Holder 是单个page 的界面，你可以new 一个 layout ，然后写你需要的布局。这个就像使用 ListView 的Holder方式一样。

**Comment by lowfiend** [comment]
图片出来了，但是文字没跟着动，我再试试看，谢谢

**Comment by saiwu-bigkoo** [comment]
每次在updateUI里面，文字控件setText 就行了。

**Comment by lowfiend** [comment]
有放了，但是不知道为何没执行

**Comment by 919317632** [comment]
在updateUI中使用Glide加载图片（使用的createView方法的context）会出现java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity，把Context通过构造方法从界面中传进来，再使用这个context作为Glide的参数就不会报错，我猜应该是createView方法里的context持有了某个子线程的外部引用

**Comment by saiwu-bigkoo** [comment]
@919317632 UpdateUI(Context context,int position,T data);  UpdateUI里面有提供了context，不需要你保存createView的context。我再排查看看createView的问题是什么情况

**Comment by 919317632** [comment]
嗯，我是在createView里面new 的ImageView，Glide调用的是imageview.getContext()，所以是用的createView里的Context

**Comment by saiwu-bigkoo** [comment]
@919317632 Glide 应该是要在application 中初始化吧，不应该用imageview.getContext()

**Comment by 919317632** [comment]
我封装了一层Glide的显示，Glide.with(context)嘛，这里面的context是直接用的传过来的imageView的getContext()，貌似昨天更新的2.0.2又不会出现那个问题……2.0.2只是改了个itemClick啊。。莫名其妙

**Comment by nukc** [comment]
@919317632 我用的就是Glide，没有问题。
使用的时候在UpdateUI里就好了，你试试?。

```java
@Override
    public void UpdateUI(Context context, int position, BannerBean data) {
        Glide.with(context)
                .load(data.getImgurl())
                .into(imageView);
    }
```

**Comment by GraysonGX** [comment]
您好！
该框架有实现点击放大图片的功能吗？
