### ISSUE TITLE
first item click not fired up

### ISSUE THREAD

**Issue by gewuxy** [saiwu-bigkoo/Android-ConvenientBanner#66]
I use AsynHttpClient,when success,i setPages and item click listener,but the first item click event is not fired,others are ok,if I set on item click listener in onCreateView(),it is normal,anyone suffer？

**Comment by saiwu-bigkoo** [comment]
You can setPage in onCreate add set itemclick, when  AsynHttpClient  success, you can change mData, add call ConvenientBanner notifyDataSetChange

**Comment by saiwu-bigkoo** [comment]
hey, I fixed the setOnItemClickListener Bug. You can update 2.0.2。
