### ISSUE TITLE
listView headerView 里加这个空间还是不能点击啊？

### ISSUE THREAD

**Issue by pickyourself** [saiwu-bigkoo/Android-ConvenientBanner#67]
View banner = LayoutInflater.from(getContext()).inflate(R.layout.header_banner, null);
        convenientBanner = (ConvenientBanner) banner.findViewById(R.id.convenient_banner);
        listView.addHeaderView(banner,null,false);

**Comment by pickyourself** [comment]
convenientBanner.setOnItemClickListener(new OnItemClickListener() {
                    @Override
                    public void onItemClick(int position) {
                        ToastUtils.showShort(getContext(), "cilck++++: " + position + "");
                        Log.d("123", "aaadad");
                    }
                });

**Comment by saiwu-bigkoo** [comment]
更新下2.0.2,最新的MainActivity里面也加入了addHeaderView例子demo，这次应该可以了

**Comment by pickyourself** [comment]
更新后点击还是没效果啊
