### ISSUE TITLE
手动划然后速度超快

### ISSUE THREAD

**Issue by lowfiend** [saiwu-bigkoo/Android-ConvenientBanner#68]
如果自己手动划然后速度超快，会出现这个然后banner卡住

The application may be doing too much work on its main thread

过一会就正常了，是正常的?

**Comment by winner3811** [comment]
起先不开起网络，加载完activity，打开网络，会出问题，你看看

**Comment by winner3811** [comment]
我说的是加载远程图片的

**Comment by saiwu-bigkoo** [comment]
compile 'com.bigkoo:convenientbanner:2.0.3' 试试新版本

**Comment by lowfiend** [comment]
用的就是新版本

您有试过吗 滑很快 就会lag

**Comment by saiwu-bigkoo** [comment]
我用尽所有力气滑动也没能测出来，你是不是把setScrollDuration设置成极快了呢。另外这个新版本没有放上github的，不是你之前用的那个版本。

**Comment by lowfiend** [comment]
我是用Module方式依赖，gradle 找不到你的库
setScrollDuration 我没设置

**Comment by saiwu-bigkoo** [comment]
hello，你再试试新的依赖地址，现在确定可以了
