### ISSUE TITLE
放在recyclerview头部出现空白

### ISSUE THREAD

**Issue by LeonJavaAndroid** [saiwu-bigkoo/Android-ConvenientBanner#70]
我将这个控件放在recyclerview的一个头部item中，当它滚动到最后一页时，我将列表滑到底部，然后在它正要切换到第一页的那个时间，滑动列表到顶部，banner上显示空白

**Comment by saiwu-bigkoo** [comment]
你可以试试demo 的recyclerview add Header方式

**Comment by LeonJavaAndroid** [comment]
直接安装Demo，试过了也是一样的空白

**Comment by kaikaifly** [comment]
我的gridviewd 的header中使用也出现白屏的现象

**Comment by saiwu-bigkoo** [comment]
compile 'com.bigkoo:convenientbanner:2.0.3' 试试新版本，我还没提交到github，顺便帮我测试下，如果能解决白屏问题我就放上github

**Comment by LeonJavaAndroid** [comment]
你好，刚使用了你的新版本，测试过暂时没发现空白，谢了！




------------------ 原始邮件 ------------------
发件人: "sai";<notifications@github.com>;
发送时间: 2015年12月23日(星期三) 下午5:40
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 
抄送: "丶NeverGone"<1965976573@qq.com>; 
主题: Re: [Android-ConvenientBanner] 放在recyclerview头部出现空白 (#70)




compile 'com.bigkoo:convenientbanner:2.0.3' 试试新版本，我还没提交到github，顺便帮我测试下，如果能解决白屏问题我就放上github

**Comment by LeonJavaAndroid** [comment]
请问啥时候把新的版本更新到github上面去，我们这边的需求需要改点代码，就是图片下面有几个小点的indicator，需要放到右边而不是居中




------------------ 原始邮件 ------------------
发件人: "sai";<notifications@github.com>;
发送时间: 2015年12月23日(星期三) 晚上8:22
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 
抄送: "丶NeverGone"<1965976573@qq.com>; 
主题: Re: [Android-ConvenientBanner] 放在recyclerview头部出现空白 (#70)




Closed #70.

**Comment by saiwu-bigkoo** [comment]
新版本这两天没问题我就放上来，但指示器在右边的接口一直都有的，直接可以支持。

**Comment by LeonJavaAndroid** [comment]
目前提供的方法是有在右边的，但是没有垂直居中




------------------ 原始邮件 ------------------
发件人: "sai";<notifications@github.com>;
发送时间: 2015年12月24日(星期四) 中午11:23
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 
抄送: "丶NeverGone"<1965976573@qq.com>; 
主题: Re: [Android-ConvenientBanner] 放在recyclerview头部出现空白 (#70)




新版本这两天没问题我就放上来，但指示器在右边的接口一直都有的，直接可以支持。

**Comment by saiwu-bigkoo** [comment]
已上传
