### ISSUE TITLE
用本地图片作为localImages，往左边滑动时会出现空白页面，往右边滑没有

### ISSUE THREAD

**Issue by minyangx** [saiwu-bigkoo/Android-ConvenientBanner#71]

**Comment by saiwu-bigkoo** [comment]
compile 'com.bigkoo:convenientbanner:2.0.3' 试试新版本，我还没提交到github，顺便帮我测试下，如果能解决白屏问题我就放上github

**Comment by minyangx** [comment]
compile 'com.bigkoo:convenientbanner: 2.0.2' 会报错，应该是2.0.2的用法和之前版本的用法不一样了

**Comment by minyangx** [comment]
测试OK
