### ISSUE TITLE
做为listView的headerView 从最后一张图片滚到第一张时，第一张图片白屏

### ISSUE THREAD

**Issue by kaikaifly** [saiwu-bigkoo/Android-ConvenientBanner#72]
做为listView的headerView 从最后一张图片滚到第一张时，第一张图片白屏

**Comment by kaikaifly** [comment]
是做为gridview的headerView

**Comment by kaikaifly** [comment]
手动滑动没事，自动滑动到第一张就空白了

**Comment by saiwu-bigkoo** [comment]
compile 'com.bigkoo:convenientbanner:2.0.3'   试试新版本，我还没提交到github，顺便帮我测试下，如果能解决白屏问题我就放上github

**Comment by kaikaifly** [comment]
没事了，能说下怎么解决的么？还看了下你的源码

**Comment by saiwu-bigkoo** [comment]
逻辑改了，原本是  012345  －》 50123450 ，现在是  012345012345012345 －》 当为item0 的时候， 在finishUpdate的时候变为 第二个0，最后的Count－1 的item 5 变为 第二个5

**Comment by kaikaifly** [comment]
好的，太感谢你了!!!
