### ISSUE TITLE
第四张图片里面的控件点击失效

### ISSUE THREAD

**Issue by EslYz** [saiwu-bigkoo/Android-ConvenientBanner#74]
每个item里面有两个textview和一张图片，给其中一个textview设置了监听，只要不是4的倍数，点击事件都可以响应，4的倍数就不行，给图片设置监听可以进去

**Comment by guomin0999** [comment]
可能是你使用的切换动画有关,试试DefaultTransformer

**Comment by saiwu-bigkoo** [comment]
有动画效果会有这个问题，不设动画即可
