### ISSUE TITLE
在Fragment中

### ISSUE THREAD

**Issue by lkwdzh** [saiwu-bigkoo/Android-ConvenientBanner#82]
在Fragment中，每次我切换fragment然后返回时，指示页数的点会增多

**Comment by saiwu-bigkoo** [comment]
你是不是切换回来的时候有做ConvenientBanner改变的操作。你切换返回之后 ConvenientBanner.notifyDataSetChanged 试试。

**Comment by lkwdzh** [comment]
多谢啦，我刚刚发现原来是存放图片的list集合没有清空




------------------ 原始邮件 ------------------
发件人: "sai";<notifications@github.com>;
发送时间: 2016年1月15日(星期五) 下午2:14
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 
抄送: "拔山"<771915131@qq.com>; 
主题: Re: [Android-ConvenientBanner] 在Fragment中 (#82)




你是不是切换回来的时候有做ConvenientBanner改变的操作。你切换返回之后 ConvenientBanner.notifyDataSetChanged 试试。
