### ISSUE TITLE
使用PageTransformer，长时间运行会导致黑屏

### ISSUE THREAD

**Issue by LinJZong** [saiwu-bigkoo/Android-ConvenientBanner#83]
查看Log日志发现是GPU过载了，看了下源码，使用的循环方式是使用设置超大值的方式，无法进行界面缓存，建议更换成新版的LoopingViewPager。
优化后已解决问题。

**Comment by saiwu-bigkoo** [comment]
很多使用者反馈用LoopingViewPager会有白屏和6.0版本卡顿现象，最后我才无奈改用超大值。2.0.2 版本是LoopingViewPager
