### ISSUE TITLE
UpdateUI 里面设置的imageview 设置tag 会报错

### ISSUE THREAD

**Issue by tanranran** [saiwu-bigkoo/Android-ConvenientBanner#9]
原因是应为CBPageAdapter里面的geteview 也设置了tag  .......获取到了我在UpdateUI 里面设置的.然而类型不对就挂掉了......我的处理方式是imageView.setTag(R.id.tag_1,uri); 这样解决的

**Comment by saiwu-bigkoo** [comment]
对的，为了缓存getview里面是set了tag的所以你的imageview不能直接setTag
